// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7qlzamK5SXXz1m3CvTNpB_VEKAx8lBrs',
    appId: '1:665640994156:web:e7fb486b10a7e32c73df49',
    messagingSenderId: '665640994156',
    projectId: 'chatingroups-dcb9d',
    authDomain: 'chatingroups-dcb9d.firebaseapp.com',
    storageBucket: 'chatingroups-dcb9d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqbnI-tKxDK5hU039J97seSo46qawvB-I',
    appId: '1:665640994156:android:c70bb70bd4f8121473df49',
    messagingSenderId: '665640994156',
    projectId: 'chatingroups-dcb9d',
    storageBucket: 'chatingroups-dcb9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMKKuAewF2Btmq9ebRwpGmJn3VqsnN-II',
    appId: '1:665640994156:ios:f7bbd2228e9e8e5073df49',
    messagingSenderId: '665640994156',
    projectId: 'chatingroups-dcb9d',
    storageBucket: 'chatingroups-dcb9d.appspot.com',
    iosBundleId: 'com.example.chatInGroups',
  );
}
